// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebLaserTag.Data;

namespace WebLaserTag.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191009104844_newModel")]
    partial class newModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("WebLaserTag.Models.PlayerData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrentState");

                    b.Property<bool>("HasFlag");

                    b.Property<string>("Name");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<double>("XGeo");

                    b.Property<double>("YGeo");

                    b.HasKey("Id");

                    b.ToTable("PlayersData");
                });
#pragma warning restore 612, 618
        }
    }
}
